### ISSUE TITLE
What happened to Ant?

### ISSUE THREAD

**Issue by scoopgracie** [MaxBittker/sandspiel#103]
Ant was a new element that appeared on sandspiel.club, but not here. It has now been removed. Will it be added back?

**Comment by labbo-lab** [comment]
it was accidently added in, and was deleted by max because it bothered him to leave it unfinished

**Comment by scoopgracie** [comment]
Okay, thanks.

**Comment by MaxBittker** [comment]
yes sorry

**Comment by scoopgracie** [comment]
Okay. Will it come back?
