### ISSUE TITLE
Add email address, phone number, url and obscenity filter to project name to discourage innapropriate project names server-side

### ISSUE THREAD

**Issue by hello-smile6** [MaxBittker/sandspiel#108]
I have noticed that 90% of the projects are inappropriate and that Sandspiel has been turned into a chat room. If a PHP script only shows inappropriate projects to email and IP addresses where they are created, then people will have no idea that their inappropriate content cannot be seen. I am tired of obscenity.

**Comment by keblou** [comment]
This is a major issue. It’s an interesting however there is an abundance of inappropriate content.

**Comment by labbo-lab** [comment]
the chat room part i dont see anything wrong with, just people making new
friends, but the inappropriate part i agree with
it would be nice to see a decline in inappropriate submissions on sandspiel

**Comment by MaxBittker** [comment]
im trying my best to ban it
