### ISSUE TITLE
Report button 

### ISSUE THREAD

**Issue by cinnamon222** [MaxBittker/sandspiel#109]
Several others have said there report button doesn’t work. This is bad because it means people can’t report sexual posts that are harassing others. Please, please try to fix this. Thank you.

**Comment by hello-smile6** [comment]
It does work, but only temporarily. It's good that it only works temporarily, or malicious users could force others to stop posting, or even create an automated system that reports every post as soon as it is posted. Still, there needs to be more moderation and a profanity filter. If the IP addresses of malicious posts and the accounts of malicious posts were banned, there wouldn't be as much of a problem.

**Comment by hello-smile6** [comment]
I see that this has been implemented.
