### ISSUE TITLE
Offline support?

### ISSUE THREAD

**Issue by KevinMGranger** [MaxBittker/sandspiel#11]
You can't use the page if you save it through the web browser. It looks like the cause is the wasm being fetched dynamically after being loaded.

Is there a way to support offline usage?

**Comment by MaxBittker** [comment]
Good question, I think that dropping in a service worker would fix this, something I'm looking to implement so it works as a progressive web app on people's phones

**Comment by g-ortuno** [comment]
It will also work on Desktop: https://developers.google.com/web/progressive-web-apps/desktop

**Comment by MaxBittker** [comment]
https://github.com/NekR/offline-plugin/pull/410

**Comment by MaxBittker** [comment]
I think I fixed this
