### ISSUE TITLE
Log-in

### ISSUE THREAD

**Issue by hellobot2001** [MaxBittker/sandspiel#117]
I’ve been trying to log in with my google account, as it is the only one I have- it’s not working! Can you fix this?

**Comment by MaxBittker** [comment]
can you post a screenshot of what the login looks like for you? is it three buttons or a single email text input field?

**Comment by hellobot2001** [comment]
No, it appears it was just a bug- or something. Maybe I just did it late.
Either way, I'm logged In now.
