### ISSUE TITLE
(mobile) Material selection buttons not scrollable

### ISSUE THREAD

**Issue by kjleitz** [MaxBittker/sandspiel#12]
This is a mixture of a bug report and a feature request: the simulator plays pretty well on mobile, but a good number of the materials are inaccessible due to overflow of the sidebar. If the sidebar were scrollable, it would likely fix this issue.

**Comment by kjleitz** [comment]
Aaaaaand I went back to sandspiel.club in mobile Chrome and the buttons are now pinned to the top, rather than to the left. Not sure why I got that view previously. I'll leave this open in case it's reproducible somehow.

**Comment by kjleitz** [comment]
Back after switching my tab to return to sandspiel:

![screenshot_20181217-110802](https://user-images.githubusercontent.com/18669659/50099487-3edb9b80-01ec-11e9-979b-cfe9325913da.png)

**Comment by dominic-03** [comment]
Try rotating sideways then vertical again.
BTW your tabs icon is funny :D

**Comment by MaxBittker** [comment]
this is fixed now i think

**Comment by kjleitz** [comment]
@dominic-03 that's what happens when you're a tab hoarder and you have > 100 tabs open 😅
