### ISSUE TITLE
Suggestion: Host sand spiel from github.

### ISSUE THREAD

**Issue by forg-man** [MaxBittker/sandspiel#121]
**actual thing**: 
recently my districts public education committee decided to get a lot stricter on internet policies and they recently blocked your website categorizing it as adult content... some of my favorite chromebook games migrated to hosting on github to get around this. (like [CelesteClassic](https://celesteclassic.github.io) and [adarkroom](http://doublespeakgames.github.io/adarkroom/)) is there anyway you could also host your game on a github.io link like you did with the prototype? 

**one more thing**:
I love how you completely revamped the biological/ecosystem aspect from danball. how ever I would love to add mechanical concepts like wireworld and langton's ant, or something of my own that can be described as a 2d-minecraft-redstone-piston-automata. if you are interested please let me know. 

**one one more thing**:
 I tried making something to do with automata with nothing but my heavily restricted school chromebook and I can't resist sharing my [results](https://colab.research.google.com/drive/11h_2WiBnL9a1SBGd9EoOC7ZH1VF3WPl4  )
also, the founder of autodesk made a web automata sandbox thats not as interactive but it's still very neat. https://www.fourmilab.ch/cellab

**Comment by MaxBittker** [comment]
super cool work with your CA system!! I will keep this in mind and maybe host on github in the future!

**Comment by MaxBittker** [comment]
thanks for the nice message. Sorry your laptop is so locked down. have you tried the game i'm working on? 
https://maxbittker.github.io/alchemy-online/

**Comment by Adithr123** [comment]
I would aslo like it to be hosted on github. By any chance, is there a way to run it on repl.it?

**Comment by hello-smile6** [comment]
> I would aslo like it to be hosted on github. By any chance, is there a way to run it on repl.it?

You can run it on Replit. In fact, you can run it anywhere. Wait a moment.

**Comment by hello-smile6** [comment]
Here. `sp-client.html` lets you look at Sandspiel, `sandspiel.html` lets you do everything else.
[sandspiel-offline.zip](https://github.com/MaxBittker/sandspiel/files/7800407/sandspiel-offline.zip)

**Comment by MaxBittker** [comment]
did you make that client? nice work!

**Comment by hello-smile6** [comment]
> did you make that client? nice work!

Made the `sp-client.html` file. As for the main sandspiel part, I just edited the JS files to point to relative directories and used the URL for my own copy of the WASM file.

**Comment by Adithr123** [comment]
how do i work it? I unziped it, but it wont load.

**Comment by Adithr123** [comment]
![image](https://user-images.githubusercontent.com/85714072/148128203-8b9dbfcf-e025-4442-9a22-aa6fde1acc45.png)

**Comment by Adithr123** [comment]
can you try running it then send me a link to the project?

**Comment by hello-smile6** [comment]
> ![image](https://user-images.githubusercontent.com/85714072/148128203-8b9dbfcf-e025-4442-9a22-aa6fde1acc45.png)

Open https://sandspiel.adith08.repl.co/sandspiel.html or do `mv sandspiel.html index.html`

**Comment by Adithr123** [comment]
![image](https://user-images.githubusercontent.com/85714072/148136425-a98c2dbd-d821-430b-8310-4b1a1b9ba7b5.png)

**Comment by Adithr123** [comment]
![image](https://user-images.githubusercontent.com/85714072/148136452-7e5d2d88-d8f6-4d9c-aa3b-23f59fbde19c.png)

**Comment by hello-smile6** [comment]
> ![image](https://user-images.githubusercontent.com/85714072/148136425-a98c2dbd-d821-430b-8310-4b1a1b9ba7b5.png)

Okay, could you show the output of `ls`?

**Comment by Adithr123** [comment]
ls?

**Comment by Adithr123** [comment]
https://replit.com/join/mjsrmnylob-adith08 use to colab on repl.it

**Comment by hello-smile6** [comment]
> https://replit.com/join/mjsrmnylob-adith08 use to colab on repl.it

Okay

**Comment by Adithr123** [comment]
https://replit.com/join/ztvewpqdve-adith08

**Comment by Adithr123** [comment]
![image](https://user-images.githubusercontent.com/85714072/148137859-0391321c-e92d-45f0-a1ab-9f57b703c17e.png)

**Comment by hello-smile6** [comment]
> ![image](https://user-images.githubusercontent.com/85714072/148137859-0391321c-e92d-45f0-a1ab-9f57b703c17e.png)

Yep.

**Comment by Adithr123** [comment]
also, browsing doesnt work, but overall, i like it. Than you.

**Comment by Adithr123** [comment]
https://sandspeil2.adith08.repl.co/ link for anyone who wants it.

**Comment by Adithr123** [comment]
> **actual thing**: recently my districts public education committee decided to get a lot stricter on internet policies and they recently blocked your website categorizing it as adult content... some of my favorite chromebook games migrated to hosting on github to get around this. (like [CelesteClassic](https://celesteclassic.github.io) and [adarkroom](http://doublespeakgames.github.io/adarkroom/)) is there anyway you could also host your game on a github.io link like you did with the prototype?
> 
> **one more thing**: I love how you completely revamped the biological/ecosystem aspect from danball. how ever I would love to add mechanical concepts like wireworld and langton's ant, or something of my own that can be described as a 2d-minecraft-redstone-piston-automata. if you are interested please let me know.
> 
> **one one more thing**: I tried making something to do with automata with nothing but my heavily restricted school chromebook and I can't resist sharing my [results](https://colab.research.google.com/drive/11h_2WiBnL9a1SBGd9EoOC7ZH1VF3WPl4) also, the founder of autodesk made a web automata sandbox thats not as interactive but it's still very neat. https://www.fourmilab.ch/cellab

https://sandspeil2.adith08.repl.co/

**Comment by hello-smile6** [comment]
> > **actual thing**: recently my districts public education committee decided to get a lot stricter on internet policies and they recently blocked your website categorizing it as adult content... some of my favorite chromebook games migrated to hosting on github to get around this. (like [CelesteClassic](https://celesteclassic.github.io) and [adarkroom](http://doublespeakgames.github.io/adarkroom/)) is there anyway you could also host your game on a github.io link like you did with the prototype?
> > **one more thing**: I love how you completely revamped the biological/ecosystem aspect from danball. how ever I would love to add mechanical concepts like wireworld and langton's ant, or something of my own that can be described as a 2d-minecraft-redstone-piston-automata. if you are interested please let me know.
> > **one one more thing**: I tried making something to do with automata with nothing but my heavily restricted school chromebook and I can't resist sharing my [results](https://colab.research.google.com/drive/11h_2WiBnL9a1SBGd9EoOC7ZH1VF3WPl4) also, the founder of autodesk made a web automata sandbox thats not as interactive but it's still very neat. https://www.fourmilab.ch/cellab
> 
> https://sandspeil2.adith08.repl.co/

I'll deploy a `wget -r`'d copy of `https://sandspiel.club/school` and rewrite it a bit.

**Comment by Adithr123** [comment]
ok. thnak you so much.

**Comment by Adithr123** [comment]
new link https://sand.adith08.repl.co/

**Comment by hello-smile6** [comment]
Want a P2P link?

**Comment by Adithr123** [comment]
Sure

**Comment by Adithr123** [comment]
that would be great!

**Comment by hello-smile6** [comment]
Could someone else on Windows MacOS, or any device that can run https://beakerbrowser.com/install/ help? I need someone else to help host the P2P version. It will work on school computers, if that's all you have.

**Comment by Adithr123** [comment]
> Want a P2P link?

Yes please!

**Comment by Adithr123** [comment]
but how do i run it?

**Comment by hello-smile6** [comment]
> but how do i run it?

So, what's your OS?

**Comment by Adithr123** [comment]
im on a chromebook

**Comment by Adithr123** [comment]
and i cant eneble linux, if thats what you're thinking.

**Comment by hello-smile6** [comment]
> and i cant eneble linux, if thats what you're thinking.

Hmm. Can you open https://copy.sh/v86/ ? If so, you might be able to do a persistent (or semi-persistent) Ubuntu 10 VM and build Beaker from source.

**Comment by Adithr123** [comment]
blocked

**Comment by hello-smile6** [comment]
> blocked

Ugh. I'll launch a mirror.

**Comment by hello-smile6** [comment]
@Adithr123 What browser extension?

**Comment by Adithr123** [comment]
securely

**Comment by Adithr123** [comment]
securly

**Comment by hello-smile6** [comment]
> securely

Then there's an easy fix. https://sheeptester.github.io/longer-tweets/securly-bypass/ 🙂

**Comment by hello-smile6** [comment]
@SheepTester figured that out.

**Comment by Adithr123** [comment]
nice!

**Comment by Adithr123** [comment]
so what now?

**Comment by hello-smile6** [comment]
@Adithr123 Can you install any browser extension?

**Comment by Adithr123** [comment]
no.

**Comment by hello-smile6** [comment]
> no.

What about https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm ? You might like it. I noticed you use ABP, which is extremely CPU-intensive and ineffective. https://github.com/gorhill/uBlock/wiki/uBlock-vs.-ABP:-efficiency-compared

**Comment by Adithr123** [comment]
abp?

**Comment by Adithr123** [comment]
i cant install any extensions.

**Comment by Adithr123** [comment]
its installed by admin...

**Comment by hello-smile6** [comment]
> its installed by admin...

Huh

**Comment by Adithr123** [comment]
i uninstalled it. I meant that i can only install apps that the admin allows.

**Comment by hello-smile6** [comment]
> i uninstalled it. I meant that i can only install apps that the admin allows.

Huh

**Comment by Adithr123** [comment]
???

**Comment by hello-smile6** [comment]
> ???

Interesting that someone would let people use that but not a better extension.

**Comment by Adithr123** [comment]
ye.

**Comment by hello-smile6** [comment]
> ye.

Have you ever used dirc?

**Comment by hello-smile6** [comment]
@Adithr123

**Comment by Adithr123** [comment]
no

**Comment by hello-smile6** [comment]
> no

Okay. Does the letter P have any significance to you?

**Comment by Adithr123** [comment]
no.

**Comment by Adithr123** [comment]
should it?

**Comment by hello-smile6** [comment]
> no.

Okay. Just was wondering.

**Comment by Adithr123** [comment]
ok.

**Comment by Adithr123** [comment]
i have to go to swim, but I will be back online in about 2 hrs.

**Comment by hello-smile6** [comment]
> i have to go to swim, but I will be back online in about 2 hrs.

Okay.

**Comment by Adithr123** [comment]
I still have my phone , and I have until 5:20

**Comment by Adithr123** [comment]
So what else do u need? To make the p2p?

**Comment by Adithr123** [comment]
Also, do u have any other securly bypasses?

**Comment by hello-smile6** [comment]
> Also, do u have any other securly bypasses?

No. :( This may sound weird, but check your email. I have a theory, and I want to test it.

**Comment by hello-smile6** [comment]
Never mind

**Comment by Adithr123** [comment]
Ok

**Comment by Adithr123** [comment]
How do u know my email?

**Comment by hello-smile6** [comment]
> How do u know my email?

I don't. At least, I think I don't.

**Comment by Adithr123** [comment]
adith08@gmail.com

**Comment by hello-smile6** [comment]
Did not ask...

**Comment by Adithr123** [comment]
0K

**Comment by hello-smile6** [comment]
Delete that, or you'll start getting spam.

**Comment by Adithr123** [comment]
Way ahead of u

**Comment by Adithr123** [comment]
Deleted it as soon as u said u didn't want it

**Comment by Adithr123** [comment]
Gtg

**Comment by hello-smile6** [comment]
> Way ahead of u

LOL. Just had a theory. Also, I realized it's impossible.

**Comment by Adithr123** [comment]
I'll be back

**Comment by Adithr123** [comment]
What?

**Comment by Adithr123** [comment]
> theory

What

**Comment by hello-smile6** [comment]
> > theory
> 
> What

Never mind

**Comment by Adithr123** [comment]
what happened to the p2p?

**Comment by Adithr123** [comment]
@hello-smile6

**Comment by hello-smile6** [comment]
> @hello-smile6

Not sure

**Comment by Adithr123** [comment]
ok

**Comment by hello-smile6** [comment]
> ok

Do you have python experience? I need help with a server,

**Comment by Adithr123** [comment]
im decent

**Comment by hello-smile6** [comment]
> im decent

Okay. What's your replit username, again?

**Comment by Adithr123** [comment]
adith08

**Comment by hello-smile6** [comment]
https://replit.com/@9pfs/iso-hosting#index.js Don't wreck my server. All I need or want is CORS support.
