### ISSUE TITLE
Element properties

### ISSUE THREAD

**Issue by hellobot2001** [MaxBittker/sandspiel#122]
This is not as much of an issue as it is a suggestion, cause I’m suggesting that, when selecting an item, you can change it’s properties- this means you can make water green and flammable, or have acid act like a gas. It’d be quite interesting. Can you add it? If you do, can you make it so that when you change elements, and go back to the original form?

**Comment by hellobot2001** [comment]
Sorry if it’s too much, but is it possible to make this accessible to mobile? Thanks!

**Comment by MaxBittker** [comment]
i;m working on this in my new game!

**Comment by hellobot2001** [comment]
Quick question about said new game, will it be possible to share you creations with others, similar to how sandspiel is?
