### ISSUE TITLE
it's not working... AT ALL... I'm not a noob....

### ISSUE THREAD

**Issue by alexey-ua** [MaxBittker/sandspiel#137]
lines with "7777" made by my insertions of console::log_2 .... into source.... can't understand whats goes wrong.... keep trying....
![image](https://user-images.githubusercontent.com/83353877/116422531-822c8700-a848-11eb-88d1-c0c0e285270c.png)

**Comment by MaxBittker** [comment]
make sure you run `cargo watch -s 'wasm-pack build'` _after_ npm run start. I don't know why it needs that

**Comment by alexey-ua** [comment]
You are seems to be a good boy / baby... may be I'm wrong....  I'll try to teach you about serious programming... <br>
NEVER USE things if you don't understand their purpose or how they work <br>

cargo watch -s 'wasm-pack build' --> brief scan of docs/google - told me that 'watch' command of cargo checks for source changes in projects and then runs shell comman (swithch '-s'), shell command is 'wasm-pack build' - so first guess if you insists that it required is that there some WebAssembly code generation goes on the fly and cargo watches for new / modified files to recompile them.... <br>

but when I follow your instructions directly run 'npm run start' wait for it to compile Rust code  and web-pack-dev server to start and recompile something to those 'pack' , then run in second terminal but in project directory cargo watch -s 'wasm-pack build' I got 'error: no such command: `watch` ' <br>

I understand that 'watch' is like a plugin for 'cargo' but it need to be installed additionaly.... <br>
*****************Further - no any will to continue lose my time with such a 'project' like yours.... and you are 'dead' as programmer... <br>
I just interested in simple physics simulations like those in 'sand games' .... but it seems for me again that it easier to develop such simulations by myself in my spare time than spend this small bits of my time  to poke around those fashionable and useless   frameworks, new 'THE BEST' languages like Rust.... with super, mega 'safety' on every step you do..... <br>

I'm very good in JS and others.... but have no any time/will to spent my energy on learning "frameworks" and "languages" made by every baby even if this is supported by Mozilla, Google, Microsoft .... their Fathers  support "frameworks/languages" of their stupid babies..... without my involvement, please....

**Comment by alexey-ua** [comment]
![image](https://user-images.githubusercontent.com/83353877/117127463-c79b0800-ada4-11eb-97d3-f8cd613ad040.png)

**Comment by alexey-ua** [comment]
![image](https://user-images.githubusercontent.com/83353877/117127617-f9ac6a00-ada4-11eb-9f9a-f11e9c2827ff.png)

**Comment by alexey-ua** [comment]
![image](https://user-images.githubusercontent.com/83353877/117127777-38422480-ada5-11eb-89ac-069c926e8ed9.png)

**Comment by alexey-ua** [comment]
![image](https://user-images.githubusercontent.com/83353877/117127994-80f9dd80-ada5-11eb-81e9-51d0fca749b6.png)

error: project root does not exists <br>

no time right now to find out  what those fu**ing programmers mean by "project root" those stupid bastards even can't write good error meassages..... because they don't understand themselves anything.... just a f***ing monkeys....
