### ISSUE TITLE
relatively low framerate

### ISSUE THREAD

**Issue by benaryorg** [MaxBittker/sandspiel#14]
I don't know whether I should even file a bug report for this, but here we go.

I'm running this on GNU/Linux with Firefox 64.0 nvidia-drivers 415.18 on a GTX 970M, i7-6700HQ, and a 144Hz screen.
I'm only getting around 80-110 fps where I would expect it to go up to 144 (vsynced).
The gaming tower on Windows 10 with Firefox 65.0b5, an i7-6850K (o.c. 4GHz), Titan V and the same screen goes up to 144 (last digit switching between 4 and 5 all the time, as usual) in an instant.

Pretty sure this project isn't about graphics performance, but I thought I might mention that.

**Comment by MaxBittker** [comment]
:P nice rig! I'm interested in getting the sim to 60fps for as many low end platforms as possible, I'll consider PRs but not going to keep this issue open
