### ISSUE TITLE
Serious bug? People can take control of admin account

### ISSUE THREAD

**Issue by Cheerfulbull** [MaxBittker/sandspiel#151]
I think I have found a way people could take control of the admin account. Where should I share it?

**Comment by MaxBittker** [comment]
can you email me at maxbittker@gmail.com? Thank you Cheerful

**Comment by jahantaila** [comment]
Please share it here, we need to be able to fix this before it is to late.

**Comment by MaxBittker** [comment]
is this actually happening?
