### ISSUE TITLE
Serious Issue - Frozen Game Functionality 

### ISSUE THREAD

**Issue by jahantaila** [MaxBittker/sandspiel#152]
If a user looks at the info tab, when they go back to the game, everything is frozen in place and noting works unless you proceed to reload the page. 

After debugging, I have come to the conclusion that the cookies need to be refreshed after the info tab is clicked on 

![image](https://user-images.githubusercontent.com/75226884/127573736-1aa3f491-a56f-4664-a263-a16d7b3dc5fd.png)

If you have any questions or want me to help, please tell me and I can try to figure out a solution.

**Comment by MaxBittker** [comment]
what if you click the "play" button?

**Comment by MaxBittker** [comment]
i agree it should be more clear

**Comment by jahantaila** [comment]
Great.  Hope to see this feature implemented.
