### ISSUE TITLE
Acid shouldn't dissolve cloner

### ISSUE THREAD

**Issue by MattSPalmer** [MaxBittker/sandspiel#16]
It seems that cloner material is immune to everything except acid, which makes acid cloners pretty short-lived.

**Comment by MaxBittker** [comment]
you're probably right, I just thought it looked cool. Might change

**Comment by gocs** [comment]
neither lava

**Comment by MattSPalmer** [comment]
Definitely looks cool, can't dispute that 👍

**Comment by ghostslayer989** [comment]
If you make a plant it will also eat the cloner.

**Comment by onlymx13** [comment]
You can make acid cloners with a single pixel of cloner surrounded completely by walls except for a pixel of acid under it

**Comment by onlymx13** [comment]
I’ve uploaded a couple acid cloner things if I remember correctly.

**Comment by onlymx13** [comment]
So I don’t think this should be changed. It’s a feature, not a bug!

**Comment by MaxBittker** [comment]
agreed
