### ISSUE TITLE
Sandspiel is being <iframe> 'd in another ebsite

### ISSUE THREAD

**Issue by Bulmenisaurus** [MaxBittker/sandspiel#167]
Not sure if you are aware of this but a website ([silvergames.com](https://www.silvergames.com/en/falling-sand))  is directly embedding your game inside an iframe:

<img width="1437" alt="Image of sanspiel being in another site" src="https://user-images.githubusercontent.com/63682890/141212291-7974cb1a-f301-4a33-8f2c-d3d9ec3ae842.png">
<img width="712" alt="Screenshot of the image embedding sandspiel" src="https://user-images.githubusercontent.com/63682890/141212338-6ccae201-e46a-4bf8-ad35-06ae5a082217.png">

You could try and stop this by adding an [`X-frame-options`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options) header to your site :)

**Comment by MaxBittker** [comment]
thanks for letting me know. I knew and I guess I'm fine with it, but I should add a watermark or something so people can know the real URL
