### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by nicebenny23** [MaxBittker/sandspiel#169]
Add an explosive blockno gravity and a fuse

**Comment by MaxBittker** [comment]
i think those are good ideas

**Comment by hello-smile6** [comment]
> i think those are good ideas

Will they be done?

**Comment by MaxBittker** [comment]
no

**Comment by hello-smile6** [comment]
> no

Why not?

**Comment by MaxBittker** [comment]
I might do a fuse

**Comment by MaxBittker** [comment]
there are already explosives

**Comment by hello-smile6** [comment]
> I might do a fuse

Okay. Could you create a beta version of Sandspiel?
