### ISSUE TITLE
Indestructible walls are not actually indestructible

### ISSUE THREAD

**Issue by jangxx** [MaxBittker/sandspiel#20]
It's possible to chip away walls by firing large amounts of fireworks at them.

Demo setup: https://i.imgur.com/um8XZ5S.png

A cloner wrapped in dust with a small ignition fire besides it at the bottom and another cloner with fireworks wrapped around it at the top.
The bottom cloner creates an infinite fire, and shoots the firework particles into the wall above. These fireworks somehow destroy parts of the "indestructible" wall, until they made their way through it.

The setup in action: https://gfycat.com/EnchantedShowyLacewing

I'm guessing this is not intended, but a fun effect nonetheless.

**Comment by MaxBittker** [comment]
cool find! I'm going to keep this open for now but not high priority to fix because I kind of like it

**Comment by MaxBittker** [comment]
not going to fix this, I think it's good
