### ISSUE TITLE
Smokes not interact with wall

### ISSUE THREAD

**Issue by supernovalx** [MaxBittker/sandspiel#30]
This can be seen by putting a fire under a wall
![image](https://user-images.githubusercontent.com/22390732/50173906-59685e80-032b-11e9-869a-006209eb73b9.png)

**Comment by MaxBittker** [comment]
I agree, this will be tricky to fix but I have some ideas based on http://developer.download.nvidia.com/books/HTML/gpugems/gpugems_ch38.html

**Comment by supernovalx** [comment]
It would be really satisfied to see that effect worked properly

**Comment by MaxBittker** [comment]
https://dan-ball.jp/en/javagame/dust/ has fluid collision only with the special "block" element which is lower resolution

**Comment by MaxBittker** [comment]
but does have it, and it enables cool stuff

**Comment by MaxBittker** [comment]
just fixed this, there's more work to do because the walls now absorb some of the wind instead of deflecting 100% of it, but it's an improvement
