### ISSUE TITLE
Fire gets triggered with oil, dust and wind

### ISSUE THREAD

**Issue by r00ster91** [MaxBittker/sandspiel#37]
To bake the bug, add the following ingredients into your pot:
* 1x Oil
* 1x Dust
* 1x Wind

So let's start with the oil:
![oil](https://user-images.githubusercontent.com/35064754/50382643-a4280480-06a4-11e9-8bc5-2d9a9670515f.png)
Then a little bit of dust:
![dust](https://user-images.githubusercontent.com/35064754/50382663-c4f05a00-06a4-11e9-8bc6-2eb5a7b5052a.png)
And then heat up your pot by adding wind!
![wind](https://user-images.githubusercontent.com/35064754/50382666-e6514600-06a4-11e9-883d-d137062eb346.png)
It begins to burn! Why? Well I'm not sure myself. Seems like a bug to me. Or am I understanding something wrong?

**Comment by MaxBittker** [comment]
this is actually working as intended, the dust combusts if it experiences high pressure!
https://github.com/MaxBittker/sandspiel/blob/master/crate/src/species.rs#L133
