### ISSUE TITLE
clear screen in safari

### ISSUE THREAD

**Issue by mikowiec** [MaxBittker/sandspiel#49]
Precondition:
- MacBook Pro, macOS Sierra 10.12.6
- Safari 10.1.2
- Chrome 70

Observed clean screen in safari, after loading, 
Error Message: `ReferenceError: Can't find variable: WebAssembly`

App works nice in Chrome browser, but frame rate is not high :)

**Comment by MaxBittker** [comment]
https://caniuse.com/#feat=wasm 
Requires Safari 11 to use webassembly, sorr


I'm surprised that frame rate is bad on chrome, how low is it?
