### ISSUE TITLE
'Browse' broken

### ISSUE THREAD

**Issue by dominic-03** [MaxBittker/sandspiel#57]
When I click browse the window just blinks for less than half a second and disappears.

(iPad 6, Safari 12, iOS 12.2, WebGL 2.0)

**Comment by MaxBittker** [comment]
are you still getting this error? would it be possible to tell me if anything is showing up in the development console?

**Comment by dominic-03** [comment]
It seems to have stopped; also, I'm on an iPad and therefore I can't get a development console.

**Comment by MaxBittker** [comment]
Thanks for opening the issue @dominic-03  and let me know if it returns! FWIW, that sounds like it _might_ be the behavior when there it no network connection? 

How does the game run on an ipad by the way? any issues with FPS, touch reactions, or UI layout?

**Comment by dominic-03** [comment]
I did have an internet connection when I observed it not working, but it was at school; that might have been the problem.

Works excellent on iPad - consistent 60 fps usually! UI works / looks great.
