### ISSUE TITLE
Water is not liquid, not going up under pressure

### ISSUE THREAD

**Issue by vi** [MaxBittker/sandspiel#61]
I expect it to approximate [communicating vessels](https://en.wikipedia.org/wiki/Communicating_vessels),  but currently it behaves more like water-coloured sand.

Can water particles be set up to track pressure and sometimes move up if there is enough pressure?

**Comment by MaxBittker** [comment]
I want to improve the horizontal flow of water, but I think that actually modeling communicating vessels would be too much complexity for the liquids of the game to track and I'm going to mark this as won't fix.
