### ISSUE TITLE
Request: Project infos for contributors

### ISSUE THREAD

**Issue by Tango1266** [MaxBittker/sandspiel#77]
Hi there, 
I very much like the project for various reasons, mostly because I want to get into WASM and Rust. I would like to contribute in future and would appreciate if there were some kind of introduction for potential less experienced contributors. 

Some information (what and whys) on the project structure, architecture and roadmap would be very helpful for me and maybe others to get started quickly.

**Comment by MaxBittker** [comment]
sorry, but I treat this like a personal creative project and the code is on github primarily to as a communication tool right now.
I don't really have a single direction or roadmap laid out.
If you want to tinker with the game or fork it please feel free to make it your own, and I'm happy to consider questions, feature requests, or PRs  if you want to contribute specific things back
