### ISSUE TITLE
Wall is destructible

### ISSUE THREAD

**Issue by kj7rrv** [MaxBittker/sandspiel#89]
Steps to reproduce:
1. Click pause
2. Create a 1px line of Wall
3. Put a pixel or two of Fire near it
4. Cover the entire thing with Rocket
5. Press Play

**Comment by hello-smile6** [comment]
@MaxBittker I suggest leaving this bug unresolved because it is a good way to let people be creative on [Sandspiel](https://sandspiel.club/).

> Please consider leaving it intact.
