### ISSUE TITLE
The Inappropriate Stuff People Are Posting

### ISSUE THREAD

**Issue by Hoi-Why-Am-I-Here** [MaxBittker/sandspiel#92]
Everyone is treating the site like an online dating website. Everyone is sending pictures of naked people ar whatever. It's very disturbing. I suggest you add an inappropriate stuff detector and the detector will delete the inappropriate part of the picture. Do it or else I'm never visiting Sandspiel ever again.

**Comment by scoopgracie** [comment]
1. "Delete the inappropriate part" would be next to impossible. A __very__
good NN __might__ be able to completely block inappropriate stuff, but it
would be a huge effort.
2. You can still play with the rest of it and just ignore the sharing
feature. That's what I do anyway.

**Comment by MaxBittker** [comment]
hi - 
I'm really sorry that it's gotten so bad. I try to moderate it but its almost impossible to check it frequently enough to keep things out of "Recent" :/ 

Do you ever use the the "Report" function and does it feel like it works to flag things? 

I need to make a better solution but I haven't been able to devote enough time to it. The only thing I think know of that would work might be requiring email verification to post, and building a banning mechanism.

**Comment by lcook14** [comment]
I think sandspiel is excellent. I have issues with the shared projects too.
Is it possible to make a version without the upload and browse buttons? Then you can have the best of both worlds.

I'd like to share this to the kids in my school but can't because of the dodgy elements to the browse area.

Either way, great job in creating this.

**Comment by scoopgracie** [comment]
That would be nice. I would use that.

**Comment by MaxBittker** [comment]
this version has no browse: 

https://sandspiel.club/school
