### ISSUE TITLE
Bug with wind never ending

### ISSUE THREAD

**Issue by Stryp0** [MaxBittker/sandspiel#95]
Happening on my Google Chrome, version 83.0.4103.61. Tested in Incognito and all extensions disabled, it doesn't affect the bug.
Does not happen on Chrome 81.0.4044.129 or on Edge 80.0.361.66.
Edit: Also occurs on Edge 83.0.478.44 but **not on Firefox 77.0.1**, so it's probably a Chromium-related issue.
![ezgif-3-fe3d3d94d458](https://user-images.githubusercontent.com/38134288/83508877-d90bce00-a4ca-11ea-8c06-664999e8263e.gif)

**Comment by MaxBittker** [comment]
:O

**Comment by Stryp0** [comment]
Fixed with Chrome  83.0.4103.97.
